
package com.linkedin.learning.webservices.soap.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MySOAPEndpoint", targetNamespace = "http://soap.webservices.learning.linkedin.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MySOAPEndpoint {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.linkedin.learning.webservices.soap.stubs.SalutationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salute", targetNamespace = "http://soap.webservices.learning.linkedin.com/", className = "com.linkedin.learning.webservices.soap.stubs.Salute")
    @ResponseWrapper(localName = "saluteResponse", targetNamespace = "http://soap.webservices.learning.linkedin.com/", className = "com.linkedin.learning.webservices.soap.stubs.SaluteResponse")
    @Action(input = "http://soap.webservices.learning.linkedin.com/MySOAPEndpoint/saluteRequest", output = "http://soap.webservices.learning.linkedin.com/MySOAPEndpoint/saluteResponse")
    public SalutationResponse salute(
        @WebParam(name = "arg0", targetNamespace = "")
        SalutationRequest arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIt", targetNamespace = "http://soap.webservices.learning.linkedin.com/", className = "com.linkedin.learning.webservices.soap.stubs.GetIt")
    @ResponseWrapper(localName = "getItResponse", targetNamespace = "http://soap.webservices.learning.linkedin.com/", className = "com.linkedin.learning.webservices.soap.stubs.GetItResponse")
    @Action(input = "http://soap.webservices.learning.linkedin.com/MySOAPEndpoint/getItRequest", output = "http://soap.webservices.learning.linkedin.com/MySOAPEndpoint/getItResponse")
    public String getIt();

}
